# Generated by Django 4.1.3 on 2022-11-29 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("journal_title", models.CharField(max_length=100)),
                (
                    "content_description",
                    models.TextField(default="A generic journal", max_length=400),
                ),
                ("slug", models.SlugField(null=True, unique=True)),
            ],
            options={
                "ordering": ["journal_title"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journaly.journal",
                    ),
                ),
            ],
            options={
                "ordering": ["date_created"],
            },
        ),
    ]
