# Generated by Django 4.1.3 on 2022-11-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journaly", "0004_alter_journal_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
